app:
  name: 'reverse-proxy'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5001

grpc:
  user_host: '0.0.0.0'
  user_port: 5002
  auth_host: '0.0.0.0'
  auth_port: 5003

logger:
  log_level: 'debug'