// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: rpc_query_journal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryJournalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id       int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QueryJournalRequest) Reset() {
	*x = QueryJournalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_query_journal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJournalRequest) ProtoMessage() {}

func (x *QueryJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_journal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJournalRequest.ProtoReflect.Descriptor instead.
func (*QueryJournalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_query_journal_proto_rawDescGZIP(), []int{0}
}

func (x *QueryJournalRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *QueryJournalRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryJournalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Journal *Journal `protobuf:"bytes,1,opt,name=journal,proto3" json:"journal,omitempty"`
	Images  []*Image `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Audios  []*Audio `protobuf:"bytes,3,rep,name=audios,proto3" json:"audios,omitempty"`
}

func (x *QueryJournalResponse) Reset() {
	*x = QueryJournalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_query_journal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJournalResponse) ProtoMessage() {}

func (x *QueryJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_journal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJournalResponse.ProtoReflect.Descriptor instead.
func (*QueryJournalResponse) Descriptor() ([]byte, []int) {
	return file_rpc_query_journal_proto_rawDescGZIP(), []int{1}
}

func (x *QueryJournalResponse) GetJournal() *Journal {
	if x != nil {
		return x.Journal
	}
	return nil
}

func (x *QueryJournalResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *QueryJournalResponse) GetAudios() []*Audio {
	if x != nil {
		return x.Audios
	}
	return nil
}

type QueryJournalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Search   string `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Limit    int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset   int32  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *QueryJournalsRequest) Reset() {
	*x = QueryJournalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_query_journal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryJournalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJournalsRequest) ProtoMessage() {}

func (x *QueryJournalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_journal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJournalsRequest.ProtoReflect.Descriptor instead.
func (*QueryJournalsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_query_journal_proto_rawDescGZIP(), []int{2}
}

func (x *QueryJournalsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *QueryJournalsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryJournalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryJournalsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryJournalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Journals []*Journal `protobuf:"bytes,1,rep,name=journals,proto3" json:"journals,omitempty"`
	Images   []*Image   `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Audios   []*Audio   `protobuf:"bytes,3,rep,name=audios,proto3" json:"audios,omitempty"`
}

func (x *QueryJournalsResponse) Reset() {
	*x = QueryJournalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_query_journal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryJournalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJournalsResponse) ProtoMessage() {}

func (x *QueryJournalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_journal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJournalsResponse.ProtoReflect.Descriptor instead.
func (*QueryJournalsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_query_journal_proto_rawDescGZIP(), []int{3}
}

func (x *QueryJournalsResponse) GetJournals() []*Journal {
	if x != nil {
		return x.Journals
	}
	return nil
}

func (x *QueryJournalsResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *QueryJournalsResponse) GetAudios() []*Audio {
	if x != nil {
		return x.Audios
	}
	return nil
}

var File_rpc_query_journal_proto protoreflect.FileDescriptor

var file_rpc_query_journal_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6a, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x6a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x64, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x13, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x83, 0x01,
	0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x52, 0x07, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x21, 0x0a,
	0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x21, 0x0a, 0x06, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x06, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x73, 0x22, 0x78, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x86, 0x01,
	0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73,
	0x12, 0x21, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x06, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x06,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x2f, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_query_journal_proto_rawDescOnce sync.Once
	file_rpc_query_journal_proto_rawDescData = file_rpc_query_journal_proto_rawDesc
)

func file_rpc_query_journal_proto_rawDescGZIP() []byte {
	file_rpc_query_journal_proto_rawDescOnce.Do(func() {
		file_rpc_query_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_query_journal_proto_rawDescData)
	})
	return file_rpc_query_journal_proto_rawDescData
}

var file_rpc_query_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_query_journal_proto_goTypes = []interface{}{
	(*QueryJournalRequest)(nil),   // 0: pb.QueryJournalRequest
	(*QueryJournalResponse)(nil),  // 1: pb.QueryJournalResponse
	(*QueryJournalsRequest)(nil),  // 2: pb.QueryJournalsRequest
	(*QueryJournalsResponse)(nil), // 3: pb.QueryJournalsResponse
	(*Journal)(nil),               // 4: pb.Journal
	(*Image)(nil),                 // 5: pb.Image
	(*Audio)(nil),                 // 6: pb.Audio
}
var file_rpc_query_journal_proto_depIdxs = []int32{
	4, // 0: pb.QueryJournalResponse.journal:type_name -> pb.Journal
	5, // 1: pb.QueryJournalResponse.images:type_name -> pb.Image
	6, // 2: pb.QueryJournalResponse.audios:type_name -> pb.Audio
	4, // 3: pb.QueryJournalsResponse.journals:type_name -> pb.Journal
	5, // 4: pb.QueryJournalsResponse.images:type_name -> pb.Image
	6, // 5: pb.QueryJournalsResponse.audios:type_name -> pb.Audio
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_query_journal_proto_init() }
func file_rpc_query_journal_proto_init() {
	if File_rpc_query_journal_proto != nil {
		return
	}
	file_journal_proto_init()
	file_dtypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_query_journal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryJournalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_query_journal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryJournalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_query_journal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryJournalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_query_journal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryJournalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_query_journal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_query_journal_proto_goTypes,
		DependencyIndexes: file_rpc_query_journal_proto_depIdxs,
		MessageInfos:      file_rpc_query_journal_proto_msgTypes,
	}.Build()
	File_rpc_query_journal_proto = out.File
	file_rpc_query_journal_proto_rawDesc = nil
	file_rpc_query_journal_proto_goTypes = nil
	file_rpc_query_journal_proto_depIdxs = nil
}
