# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\xf7\x04\n\tAIService\x12\x8e\x01\n\x0fGenerateCaption\x12\x0f.pb.TextRequest\x1a\x10.pb.TextResponse\"X\x92\x41\x33\x12\x10Generate Caption\x1a\x1fGenerate a caption for an image\x82\xd3\xe4\x93\x02\x1c\"\x17/ai/v1/generate_caption:\x01*\x12\xac\x01\n\x14ReformatJournalEntry\x12\x0f.pb.TextRequest\x1a\x10.pb.TextResponse\"q\x92\x41\x46\x12\x16Reformat Journal Entry\x1a,Reformat a journal entry for correct grammar\x82\xd3\xe4\x93\x02\"\"\x1d/ai/v1/reformat_journal_entry:\x01*\x12\x90\x01\n\rGenerateTodos\x12\x0f.pb.TextRequest\x1a\x10.pb.TextResponse\"\\\x92\x41\x39\x12\x0eGenerate Todos\x1a\'Generate todos based on a journal entry\x82\xd3\xe4\x93\x02\x1a\"\x15/ai/v1/generate_todos:\x01*\x12\x96\x01\n\x0eSummarizeAudio\x12\x0f.pb.TextRequest\x1a\x10.pb.TextResponse\"a\x92\x41=\x12\x0fSummarize Audio\x1a*Summarize an audio file by transcribing it\x82\xd3\xe4\x93\x02\x1b\"\x16/ai/v1/summarize_audio:\x01*BxZ\x0cremind/ai/pb\x92\x41g\x12\x65\n\x0e\x41I Service API\"N\n\nAI Service\x12&https://github.com/lokissod/ai-service\x1a\x18\x64okhaihung2003@gmail.com2\x03\x31.0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014remind/ai/pb\222Ag\022e\n\016AI Service API\"N\n\nAI Service\022&https://github.com/lokissod/ai-service\032\030dokhaihung2003@gmail.com2\0031.0'
  _globals['_AISERVICE'].methods_by_name['GenerateCaption']._loaded_options = None
  _globals['_AISERVICE'].methods_by_name['GenerateCaption']._serialized_options = b'\222A3\022\020Generate Caption\032\037Generate a caption for an image\202\323\344\223\002\034\"\027/ai/v1/generate_caption:\001*'
  _globals['_AISERVICE'].methods_by_name['ReformatJournalEntry']._loaded_options = None
  _globals['_AISERVICE'].methods_by_name['ReformatJournalEntry']._serialized_options = b'\222AF\022\026Reformat Journal Entry\032,Reformat a journal entry for correct grammar\202\323\344\223\002\"\"\035/ai/v1/reformat_journal_entry:\001*'
  _globals['_AISERVICE'].methods_by_name['GenerateTodos']._loaded_options = None
  _globals['_AISERVICE'].methods_by_name['GenerateTodos']._serialized_options = b'\222A9\022\016Generate Todos\032\'Generate todos based on a journal entry\202\323\344\223\002\032\"\025/ai/v1/generate_todos:\001*'
  _globals['_AISERVICE'].methods_by_name['SummarizeAudio']._loaded_options = None
  _globals['_AISERVICE'].methods_by_name['SummarizeAudio']._serialized_options = b'\222A=\022\017Summarize Audio\032*Summarize an audio file by transcribing it\202\323\344\223\002\033\"\026/ai/v1/summarize_audio:\001*'
  _globals['_TEXTREQUEST']._serialized_start=102
  _globals['_TEXTREQUEST']._serialized_end=129
  _globals['_TEXTRESPONSE']._serialized_start=131
  _globals['_TEXTRESPONSE']._serialized_end=159
  _globals['_AISERVICE']._serialized_start=162
  _globals['_AISERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
