# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCaption = channel.unary_unary(
                '/pb.AIService/GenerateCaption',
                request_serializer=ai__service__pb2.TextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TextResponse.FromString,
                _registered_method=True)
        self.ReformatJournalEntry = channel.unary_unary(
                '/pb.AIService/ReformatJournalEntry',
                request_serializer=ai__service__pb2.TextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TextResponse.FromString,
                _registered_method=True)
        self.GenerateTodos = channel.unary_unary(
                '/pb.AIService/GenerateTodos',
                request_serializer=ai__service__pb2.TextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TextResponse.FromString,
                _registered_method=True)
        self.SummarizeAudio = channel.unary_unary(
                '/pb.AIService/SummarizeAudio',
                request_serializer=ai__service__pb2.TextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TextResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCaption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReformatJournalEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCaption': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCaption,
                    request_deserializer=ai__service__pb2.TextRequest.FromString,
                    response_serializer=ai__service__pb2.TextResponse.SerializeToString,
            ),
            'ReformatJournalEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.ReformatJournalEntry,
                    request_deserializer=ai__service__pb2.TextRequest.FromString,
                    response_serializer=ai__service__pb2.TextResponse.SerializeToString,
            ),
            'GenerateTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTodos,
                    request_deserializer=ai__service__pb2.TextRequest.FromString,
                    response_serializer=ai__service__pb2.TextResponse.SerializeToString,
            ),
            'SummarizeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeAudio,
                    request_deserializer=ai__service__pb2.TextRequest.FromString,
                    response_serializer=ai__service__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCaption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/GenerateCaption',
            ai__service__pb2.TextRequest.SerializeToString,
            ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReformatJournalEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/ReformatJournalEntry',
            ai__service__pb2.TextRequest.SerializeToString,
            ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/GenerateTodos',
            ai__service__pb2.TextRequest.SerializeToString,
            ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.AIService/SummarizeAudio',
            ai__service__pb2.TextRequest.SerializeToString,
            ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
