// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: image.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO image (
    journal_id, content
) VALUES (
    $1, $2
) RETURNING id, journal_id, content, created_at, is_embedded
`

type CreateImageParams struct {
	JournalID int64  `json:"journal_id"`
	Content   []byte `json:"content"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage, arg.JournalID, arg.Content)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Content,
		&i.CreatedAt,
		&i.IsEmbedded,
	)
	return i, err
}

const getImageOfJournal = `-- name: GetImageOfJournal :many
SELECT id, journal_id, content, created_at, is_embedded 
FROM image
WHERE journal_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetImageOfJournal(ctx context.Context, journalID int64) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImageOfJournal, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.Content,
			&i.CreatedAt,
			&i.IsEmbedded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageEmbeddingStatus = `-- name: UpdateImageEmbeddingStatus :one
UPDATE image
SET is_embedded = $1
WHERE id = $2
RETURNING id, journal_id, content, created_at, is_embedded
`

type UpdateImageEmbeddingStatusParams struct {
	IsEmbedded bool  `json:"is_embedded"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateImageEmbeddingStatus(ctx context.Context, arg UpdateImageEmbeddingStatusParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImageEmbeddingStatus, arg.IsEmbedded, arg.ID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Content,
		&i.CreatedAt,
		&i.IsEmbedded,
	)
	return i, err
}
