// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Audio struct {
	ID         int64     `json:"id"`
	JournalID  int64     `json:"journal_id"`
	Content    []byte    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	IsEmbedded bool      `json:"is_embedded"`
}

type Image struct {
	ID         int64     `json:"id"`
	JournalID  int64     `json:"journal_id"`
	Content    []byte    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	IsEmbedded bool      `json:"is_embedded"`
}

type Journal struct {
	ID         int64       `json:"id"`
	Username   string      `json:"username"`
	Title      string      `json:"title"`
	Content    pgtype.Text `json:"content"`
	Status     bool        `json:"status"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	IsEmbedded bool        `json:"is_embedded"`
}
